force-app/main/default/objects/Species__c/Species__c.object-meta.xml
<CustomObject>
    <label>Species</label>
    <nameField>
        <label>Species Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Species</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Species__c/fields/Summer_Fertilization_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Summer_Fertilization_Frequency__c</fullName>
    <label>Summer_Fertilization_Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Twice per week</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Every other week</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Every three months</fullName>
            </value>
            <value>
                <fullName>Not needed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Species__c/fields/Summer_Watering_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Summer_Watering_Frequency__c</fullName>
    <label>Summer_Watering_Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Twice per week</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Every other week</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Every three months</fullName>
            </value>
            <value>
                <fullName>Not needed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Species__c/fields/Winter_Fertilization_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Winter_Fertilization_Frequency__c</fullName>
    <label>Winter_Fertilization_Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Twice per week</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Every other week</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Every three months</fullName>
            </value>
            <value>
                <fullName>Not needed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Species__c/fields/Winter_Watering_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Winter_Watering_Frequency__c</fullName>
    <label>Winter_Watering_Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Twice per week</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Every other week</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Every three months</fullName>
            </value>
            <value>
                <fullName>Not needed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FrequencyService.cls
public with sharing class FrequencyService {

    static Map<String, Integer> daysByFrequency = new Map<String, Integer>();

    // Bloque estático de inicialización (se ejecuta la primera vez que se referencie a la clase)
    static {
        daysByFrequency.put('Daily', 1);
        daysByFrequency.put('Twice per week', 3);
        daysByFrequency.put('Weekly', 7);
        daysByFrequency.put('Every other week', 15);
        daysByFrequency.put('Monthly', 30);
        daysByFrequency.put('Every three months', 90);
        daysByFrequency.put('Not needed', 999);
    }

    static Set<Integer> summerMonths = new Set<Integer>{ 5, 6, 7, 8, 9};

    public static Integer getWateringDays(Species__c specie, DateService dateServiceInstance) {
        Integer month = dateServiceInstance.getCurrentMonth();
        if(summerMonths.contains(month)) {
            return daysByFrequency.get(specie.Summer_Watering_Frequency__c);
            // specie.Summer_Watering_Frequency__c
        } else {
            return daysByFrequency.get(specie.Winter_Watering_Frequency__c);
            // specie.Winter_Watering_Frequency__c
        }
    }

    public static Integer getFertilizationDays(Species__c specie, DateService dateServiceInstance) {
        Integer month = dateServiceInstance.getCurrentMonth();
        if(summerMonths.contains(month)) {
            return daysByFrequency.get(specie.Summer_Fertilization_Frequency__c);
            // specie.Summer_Fertilization_Frequency__c
        } else {
            return daysByFrequency.get(specie.Winter_Fertilization_Frequency__c);
            // specie.Winter_Fertilization_Frequency__c
        }
    }
}