force-app/main/default/objects/Species__c/Species__c.object-meta.xml
<CustomObject>
    <label>Species</label>
    <nameField>
        <label>Species Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Species</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Species__c/fields/Summer_Watering_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Summer_Watering_Frequency__c</fullName>
    <label>Summer_Watering_Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Twice per week</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Every other week</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Every three months</fullName>
            </value>
            <value>
                <fullName>Not needed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FrequencyServiceTest.cls
@isTest
private with sharing class FrequencyServiceTest {
    
    @isTest
    static void getWateringDays_wateringFrequencyDailyAndSummer_oneDay() {
        // TODO: mock System.today() - emular en el este en qué mes del año estoy
        // GIVEN - Creación de datos, escenario ...
        Species__c specie = new Species__c();
        specie.Summer_Watering_Frequency__c = 'Daily';
        // WHEN - Llamamos al método que queremos testear
        Integer days = FrequencyService.getWateringDays(specie);

        // THEN - Chequear el resultado esperado
        Integer expectedDays = 1;
        System.assertEquals(expectedDays, days, 'Expected 1 day returned');
    }

    @isTest
    static void getWateringDays_wateringFrequencyTwicePerWeekAndSummer_threeDays() {
        // TODO: mock System.today() - emular en el este en qué mes del año estoy
        // GIVEN - Creación de datos, escenario ...
        Species__c specie = new Species__c();
        specie.Summer_Watering_Frequency__c = 'Twice per week';
        // WHEN - Llamamos al método que queremos testear
        Integer days = FrequencyService.getWateringDays(specie);

        // THEN - Chequear el resultado esperado
        Integer expectedDays = 3;
        System.assertEquals(expectedDays, days, 'Expected 3 days returned');
    }

}