force-app/main/default/objects/Plant__c/Plant__c.object-meta.xml
<CustomObject>
    <label>Plant</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Plant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plant__c/fields/Last_Fertilized__c.field-meta.xml
<CustomField>
    <fullName>Last_Fertilized__c</fullName>
    <label>Last Fertilized</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Plant__c/fields/Last_Watered__c.field-meta.xml
<CustomField>
    <fullName>Last_Watered__c</fullName>
    <label>Last Watered</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Plant__c/fields/Next_Water__c.field-meta.xml
<CustomField>
    <fullName>Next_Water__c</fullName>
    <label>Next Water</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Plant__c/fields/Species__c.field-meta.xml
<CustomField>
    <fullName>Species__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Species</label>
    <referenceTo>Species__c</referenceTo>
    <relationshipLabel>Plants</relationshipLabel>
    <relationshipName>Plants</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Species__c/Species__c.object-meta.xml
<CustomObject>
    <label>Species</label>
    <nameField>
        <label>Species Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Species</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Species__c/fields/Summer_Watering_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Summer_Watering_Frequency__c</fullName>
    <label>Summer_Watering_Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Twice per week</fullName>
            </value>
            <value>
                <fullName>Weekly</fullName>
            </value>
            <value>
                <fullName>Every other week</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Every three months</fullName>
            </value>
            <value>
                <fullName>Not needed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PlantTriggerTest.cls
@isTest
private with sharing class PlantTriggerTest {
    
    @isTest
    static void insertPlant_lastWateredSetup_nextWateringDateCalculatedCorrectly() {

        // GIVEN
        Species__c poto = new Species__c();
        poto.Summer_Watering_Frequency__c = 'Every other week';
        insert poto;


        Plant__c plant1 = new Plant__c();
        plant1.Last_Watered__c = System.today();
        plant1.Species__c = poto.Id; // poto
        plant1.Last_Fertilized__c = System.today();

        // WHEN
        Test.startTest();
            insert plant1;
        Test.stopTest();
        // THEN
        plant1 = [SELECT Next_Water__c FROM Plant__c WHERE Id = :plant1.Id];
        System.assertEquals(System.today() + 15, plant1.Next_Water__c , '');
    }
}